project:
  type: website
  output-dir: docs


website:
  title: "Richard Aubrey White"
  body-header: <script data-goatcounter="https://rwhiteno.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  favicon: favicon.png
  navbar:
    right:
      - text: "Home"
        href: index.html
      - cv.qmd
      - publications.qmd
      - recipes.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/raubreywhite
format:
  html:
    theme: flatly
    # css: styles.css
    title-block-banner: "#b8e2f2"
    title-block-banner-color: "#000000"



