project:
  type: website
  output-dir: docs

resources:
  - "favicon.png"
  # - "CNAME"
  - "resources/*"
  - "articles/*"
  - "presentations/*"

website:
  title: "Papadopoulos Lab"
  # body-header: <script data-goatcounter="https://rwhiteno.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  favicon: favicon.png
  navbar:
    right:
      - text: "Home"
        href: index.html
      - publications.qmd
      - presentations.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/papadopoulos-lab
# format:
#   html:
#     theme: flatly
#     # css: styles.css
#     title-block-banner: "#b8e2f2"
#     title-block-banner-color: "#000000"



